on:
  push:
    branches:
      - main

jobs:
  release:
    uses: "willsoto/actions/.github/workflows/node-release.yml@5.0.0"
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
